export const routeNames = {
  LOADING: 'LOADING',
  AUTH: 'AUTH',
  MAIN_STACK: 'MAIN_STACK',
  MAIN_TAB: 'MAIN_TAB',
  FEED: 'FEED',
  POSTING: 'POSTING',
  PICK: 'PICK',
  SUBMIT: 'SUBMIT',
  POST: 'POST',
  PROFILE: 'PROFILE',
};
